apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: host-vol
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx:1.25.0
        ports:
        - containerPort: 80
          hostPort: 0
        securityContext:
          privileged: false
          capabilities:
            add:
            - CHOWN