apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx: unconfined
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostUsers: false
      securityContext:
        seLinuxOptions:
          user: "system_u"
          role: "system_r"
          type: "invalid_t"
        seccompProfile:
          type: Unconfined
        sysctls:
        - name: net.core.somaxconn
          value: "512"
      volumes:
      - name: host-vol
        hostPath:
          path: /etc
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          hostPort: 80
        securityContext:
          privileged: true
          procMount: Unmasked
          capabilities:
            add:
            - SYS_ADMIN
          seLinuxOptions:
            user: "system_u"
            role: "system_r"
            type: "invalid_t"
          seccompProfile:
            type: Unconfined
